global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['localhost:8428']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['localhost:9100']
